name: pxt-buildpr

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          sudo npm install -g pxt
          npm install
      - name: Start PXT server
        run: |
          nohup pxt serve &
          sleep 5  # Wait for server to start
        env:
          CI: true
      - name: Run unit tests
        run: npm run test:unit
      - name: Run E2E tests
        run: npm run test:e2e
        env:
          CI: true
      - name: pxt ci
        run: pxt ci
        env:
          CHROME_BIN: chromium-browser
          DISPLAY: :99.0
          CI: true
